version: "2.2"
services:
  webserver:
    image: nginx:latest
    ports:
       - "8080:80"
    volumes:
       - ./db-data:/usr/local/nginx/conf
  redis:
    image: redis
  database:
    image: postgres
    ports:
      - "5432"
    env_file: .env
    volumes:
       - ./pg-data:/var/lib/postgresql/data
