version: "2.2"
services:
  webserver:
    image: nginx:latest
    ports:
       - "8080:80"
    volumes:
       - ./db-data:/usr/local/nginx/conf
  redis:
    image: redis
  database:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: devops123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
       - ./pg-data:/var/lib/postgresql/data
